### ISSUE TITLE
Where is  "user_interface.h"?

### ISSUE THREAD

**Issue by dagnall53** [eporocrail/Eltraco#1]
The code for the servo setting tool looks very interesting, but I missed / cannot find "user_interface.h"
Can you add it to the repository or add a note to say where it is?
Many thanks
Dagnall

**Comment by eporocrail** [comment]
Dagnall,
Thanks for the remark. You got me! It is a remnant which needs to be done away with.
I am working on a new version of the software, one single software package for all types of decoder. In that version it is not present anymore.
Ellard
